# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
schedules:
- cron: "*/5 * * * *"
  displayName: Daily midnight build
  branches:
    include:
    - main

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    ScriptType: 'FilePath'
    ScriptPath: 'AuditResources.ps1'
    azurePowerShellVersion: 'LatestVersion'
